mal-IN~NotoSansMalayalam~-25
hi-IN~Kalpana~-10
tam-IN~NotoSerifTamil~-32
kan-IN~NotoSerifKannada~-35
bn-IN~NotoSansBengali~-30
as-IN~NotoSansBengali~-30
gu-IN~NotoSansGujarati~-26
mar-IN~Kalpana~-13
or-IN~NotoSerifOriya~-26
pan-IN~NotoSerifGurmukhi~-30
te-IN~NotoSerifTelugu~-30
spa-IN~NotoSans~-5
ger-IN~NotoSans~-5
fr-IN~NotoSans~-5
sspl
